# SITE CONFIGURATION
baseurl: ""
url: "http://gouy-antoine.com"
title: Antoine Gouy - Multipotentiel # site's title
description: "Addict aux startups / jeux-vidéo | Designer UI/UX | Formateur dans la tech/art | Ambassadeur Holacracy" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Antoine Gouy - Multipotentiel # blog's title
  avatar: assets/img/photo.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Libérez vos potentialités | Addict aux startups / jeux-vidéo | Designer UI/UX | Formateur dans la tech/art | Ambassadeur Holacracy </p>
  header_text_blog: <p>Le blabla d'un addict aux startups / jeux-vidéo | Designer UI/UX | Formateur dans la tech/art | Ambassadeur Holacracy</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  header_text_feature_image_blog: assets/img/pexels/book-coffee.jpeg
  footer_text: >
   Copyright Antoine Gouy© | Propulsé par <a href="https://jekyllrb.com/">Jekyll</a> avec une belle dose de <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: antoine.gouy@gmail.com
  behance: Caidezel
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: Caidezel
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/antoinegouy/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: antoinegouy
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: 
    tumblr:
    pinterest:
    pocket:
    reddit: 
    linkedin: true
    wordpress: true
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: # Enable if using math markup
  
  special_page:
    search: 
      icon: "search"
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Suivez-moi sur"
  str_rss_follow: "RSS feed"
  str_share_on: "Partagez sur"
  str_add_to: "Ajoutez à"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Article suivant"
  str_previous_post: "Article précedent"
  str_next_page: "Suivant"
  str_previous_page: "Précèdent"
  str_continue_reading: "Continuez à lire"
  str_javascript_required_disqus: "Merci d'activer JavaScript pour lire les commentaires."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
